Add bash completion
johnkerl/miller pull request #1684
Opened 2024-10-08 02:47 UTC by balki

POC for bash completion support. It does two things as for now

1. Following `then`, it completes a verb
2. When tab is hit twice after completing a verb, it shows help for the verb

### Demo

![demo](https://github.com/user-attachments/assets/6719786b-3edd-4336-ada2-f335fea7d77a)

### Setup
```
❯ mlr completion     
Usage: mlr completion SHELL
Supported shells: bash

Add below to your bashrc to enable completion
source <(mlr completion bash)

❯ mlr completion bash
complete -o nospace -o nosort -C "mlr _complete_bash" mlr

```
---
Let me know if you like the approach. Can be enhanced further
- [ ] zsh completion
- [ ] complete global flags
- [ ] complete verb flags
- [ ] complete field names from input for some verbs like `cut -f..` (extracted from first line of input in `--from` flag)

2024-10-18 16:20 UTC, balki commented
@johnkerl  Are you ok with the approach for completion? Reading flags may require bit of refactor in command line parsing logic.

2024-10-19 23:00 UTC, johnkerl commented on pkg/auxents/completion.go
> +		fmt.Println("Unsupported shell: %s\n", args[0])
```suggestion
		fmt.Printlf("Unsupported shell: %s\n", args[0])
```

2024-10-19 23:02 UTC, johnkerl commented
@balki Hi and sorry for the delay!

This is AWESOME stuff!!! 😎 

Agreed re all four checkboxes -- if you're up for it, these are all great! It's better to have some completion than none at all, so, I'm happy to take these as separate PRs.

I _think_ `bash` is more popular than `zsh` but I really don't have data -- in any case ideally one would have support for both.

I'm happy to work with you on refactoring the command-line-parsing logic ...

2024-10-19 23:02 UTC, johnkerl requested changes
Please see requested change

2024-11-01 16:59 UTC, balki commented
Thank you! Will try to work on this in next few weeks. 

Yes bash is more popular and will start with bash as it is simpler. However zsh completion is more powerful and useful. E.g the flag completion has the help text which is very helpful. And mac os default shell is zsh.

2025-04-11 18:00 UTC, J0J0 commented
Has there been any progress on this?

(Mostly, i'm asking to avoid duplicate work. If there hasn't been any work on zsh completion, i _might_ have a look at it ...)

2025-06-28 15:51 UTC, balki commented
Apologies. I am not working on this anymore for now. Anyone interested, please take over.

2026-06-21 15:41 UTC, johnkerl commented
This turns out to be really complicated for Miller ... 

Most CLI programs  have something like

```
 $ programname -a -b -cde --flag1 --flag2 filename1 filename2 etc.
```

-- crucially, there is _one_ set of flags.

Miller, by contrast, has a [structure](https://miller.readthedocs.io/en/latest/reference-main-overview/) like this:

```
$ mlr -a -b -cde --flag1 [these are flags for all of miller] verb1 -x -yz --foo [flags for verb1] then verb2 -i -jk --bar [flags for verb2]
```

I took a good long stab at this many months ago & gave up in despair.

Today I pointed Claude at it & it looks like a viable solution (there are some things AIs are indispensable for ... I'm glad we have this option now): #2096.

2026-06-21 15:41 UTC, closed without merging